resources:
  repositories:
    - repository: templates
      type: github
      endpoint: piomin
      name: piomin/azure-pipelines-templates
      ref: refs/heads/patch-2

jobs:
  - template: java-pipeline.yml@templates  # Template reference
    parameters:
      appName: 'sample-spring-kotlin-microservice'
      feedName: 'pminkows'
