resources:
  repositories:
    - repository: templates
      type: github
      name: piomin/azure-pipelines-templates

jobs:
  - template: java-pipeline.yml@templates  # Template reference
    parameters:
      appName: 'sample-spring-kotlin-microservice'
      orgName: 'pminkows'
