---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-spring-kotlin-microservice
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[master]"
#    pipelinesascode.tekton.dev/task: "git-clone"
#    pipelinesascode.tekton.dev/task-2: "maven"
#    pipelinesascode.tekton.dev/task-3: "s2i-java"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: source_branch
      value: "{{ source_branch }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: source_branch
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: git-clone
            - name: namespace
              value: openshift-pipelines
        workspaces:
          - name: output
            workspace: source
        params:
          - name: URL
            value: $(params.repo_url)
          - name: REVISION
            value: $(params.revision)
          - name: SSL_VERIFY
            value: "false"
      - name: maven-build
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: maven
            - name: namespace
              value: openshift-pipelines
        workspaces:
          - name: source
            workspace: source
        params:
          - name: JAVA_VERSION
            value: '25'
      - name: s2i-java
        runAfter:
          - maven-build
        when:
          - input: $(params.source_branch)
            operator: in
            values:
              - master
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: s2i-java
            - name: namespace
              value: openshift-pipelines
        workspaces:
          - name: source
            workspace: source
        params:
          - name: IMAGE
            value: image-registry.openshift-image-registry.svc:5000/ci/sample-spring-kotlin-microservice:$(params.revision)
          - name: BUILD_EXTRA_ARGS
            value: "-Dkotlin.compiler.daemon=false"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi